{
 "title": "k6 Prometheus",
 "description": "Visualize k6 OSS results stored in Prometheus",
 "tags": [
  "prometheus",
  "k6"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus DS", "query": "prometheus" },
   { "name": "testid", "label": "Test ID", "query": { "query": "label_values(testid)" } },
   { "name": "quantile_stat", "label": "Trend Metrics Query", "query": { "query": "metrics(k6_http_req_duration_)" } },
   { "name": "adhoc_filter", "label": "AdhocFilter" },
   {
    "name": "api_container_id",
    "label": "Container ID",
    "query": "f05aa179b8eb6fe85d248c2ff9303b1f18cac70e51d7ccfc7bff395842c5121c"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/docker/$api_container_id\"}[1m])) * 100",
     "legendFormat": "api CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{id=\"/docker/$api_container_id\"} / 1024 / 1024",
     "legendFormat": "api Mem Usage"
    }
   ]
  },
  {
   "title": "Req Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg by(test_name) (k6_http_req_duration_$quantile_stat{source=~\"k6-common\"})",
     "legendFormat": "Duration_$quantile_stat ({{test_name}})"
    },
    {
     "expr": "sum by(test_name) (irate(k6_http_reqs_total{source=~\"k6-common\", expected_response=\"false\"}[$__rate_interval]))",
     "legendFormat": "Error/s ({{test_name}})"
    }
   ]
  },
  { "title": "Performance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Performance Overview",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by(test_name) (k6_vus{source=~\"k6-common\"})",
     "legendFormat": "VUs ({{test_name}})"
    },
    {
     "expr": "avg by(test_name) (k6_http_req_duration_$quantile_stat{source=~\"k6-common\"})",
     "legendFormat": "Duration_$quantile_stat ({{test_name}})"
    },
    {
     "expr": "sum by(test_name) (irate(k6_http_reqs_total{source=~\"k6-common\"}[$__rate_interval]))",
     "legendFormat": "Req/s ({{test_name}})"
    },
    {
     "expr": "avg by(test_name) (round(k6_http_req_failed_rate{source=~\"k6-common\"}, 0.1)) * 100",
     "legendFormat": "Failed ({{test_name}})"
    },
    {
     "expr": "sum by(test_name) (irate(k6_http_reqs_total{source=~\"k6-common\", expected_response=\"false\"}[$__rate_interval]))",
     "legendFormat": "Errors ({{test_name}})"
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(irate(k6_data_sent_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "data_sent"
    },
    {
     "expr": "avg(irate(k6_data_received_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "data_received"
    }
   ]
  },
  {
   "title": "Iterations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(k6_iteration_duration_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "iteration_duration_$quantile_stat"
    },
    {
     "expr": "avg(k6_dropped_iterations_total{testid=~\"$testid\"})",
     "legendFormat": "dropped_iterations"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "HTTP requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(k6_http_reqs_total{testid=~\"$testid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP request failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peak RPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "stat",
   "description": "Select a different Stat to change the query",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(k6_http_req_duration_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Latency Timings",
   "type": "timeseries",
   "description": "Select a different Stat to change the query\n\n<a href=\"https://k6.io/docs/using-k6/metrics/reference/#http\" target=\"_blank\">HTTP-specific built-in metrics</a>",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(k6_http_req_blocked_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "http_req_blocked_$quantile_stat"
    },
    {
     "expr": "avg(k6_http_req_tls_handshaking_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "http_req_tls_handshaking_$quantile_stat"
    },
    {
     "expr": "avg(k6_http_req_sending_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "http_req_sending_$quantile_stat"
    },
    {
     "expr": "avg(k6_http_req_waiting_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "http_req_waiting_$quantile_stat"
    },
    {
     "expr": "avg(k6_http_req_receiving_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "http_req_receiving_$quantile_stat"
    },
    {
     "expr": "avg(k6_http_req_duration_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "http_req_duration_$quantile_stat"
    }
   ]
  },
  {
   "title": "HTTP Latency Stats",
   "type": "timeseries",
   "description": "Select a different Stat to change the query",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(k6_http_req_duration_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "http_req_duration_$quantile_stat"
    },
    {
     "expr": "avg(k6_http_req_duration_$quantile_stat{testid=~\"$testid\", expected_response=\"true\"})",
     "legendFormat": "success_http_req_duration_$quantile_stat"
    },
    {
     "expr": "avg(k6_http_req_duration_$quantile_stat{testid=~\"$testid\", expected_response=\"false\"})",
     "legendFormat": "errors_http_req_duration_$quantile_stat"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "http_req_s"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_errors"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"true\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_success"
    }
   ]
  },
  {
   "title": "Requests by URL",
   "type": "table",
   "description": "min/max/p95/p99 depends on the available Quantile Stats",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "avg by(name, method, status) (k6_http_req_duration_min{testid=~\"$testid\"})",
     "legendFormat": "min"
    },
    {
     "expr": "avg by(name, method, status) (k6_http_req_duration_max{testid=~\"$testid\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg by(name, method, status) (k6_http_req_duration_p95{testid=~\"$testid\"})",
     "legendFormat": "p95"
    },
    {
     "expr": "avg by(name, method, status) (k6_http_req_duration_p99{testid=~\"$testid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Checks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Checks list",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "round(k6_checks_rate{testid=~\"$testid\"}, 0.1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checks Success Rate (aggregate individual checks)",
   "type": "timeseries",
   "description": "Filter by check name to query a particular check",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "avg(round(k6_checks_rate{testid=~\"$testid\"}, 0.1)*100)",
     "legendFormat": "k6_checks_rate"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 57 },
   "options": {
    "content": "### Visualize other k6 results  \n\nAt the top of the dashboard, click `Add` and select `Visualization` from the dropdown menu. Choose the visualization type and input the PromQL queries for the `k6_` metric(s).\n\nAlternatively, click on the `Explore` icon on the menu bar and input the queries for the `k6_` metric(s). From `Explore`, you can add new Panels to this dashboard. \n\nNote that all <a href=\"https://k6.io/docs/using-k6/metrics/\" target=\"_blank\">k6 metrics</a> are prefixed with the `k6_` namespace when sent to Prometheus."
   }
  }
 ]
}